FROM python:3.11

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 5000
CMD [ "python", "restservice.py" ]